device: cuda
it: 13
Reading Data Started...
(1000, 5000, 20) (1000, 5000, 1)
(400, 5000, 20)
Fold : 0
**********************************
Folder : 0 Epoch : 0
Curr learning_rate: 0.001000000
torch.Size([32, 5000, 275]) torch.Size([32, 5000, 275])
torch.Size([32, 5000, 128])
torch.Size([32, 5000, 128])
Traceback (most recent call last):
  File "quantize.py", line 250, in <module>
    loss.backward()
  File "/work/i_kuroyanagi-1000128/virtualenvs/py36/lib/python3.6/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/work/i_kuroyanagi-1000128/virtualenvs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32, 5000, 275]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
